workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: ${{ needs.get_openai_spec_url.outputs.openapi_spec_url }}
targets:
    Java:
        target: java
        source: my-source
        publish:
            java:
                ossrhUsername: $OSSRH_USERNAME
                ossrhPassword: $OSSRH_PASSWORD
                gpgSecretKey: $JAVA_GPG_SECRET_KEY
                gpgPassPhrase: $JAVA_GPG_PASSPHRASE
                useSonatypeLegacy: true
